#include "\A3XAI\globaldefines.hpp"

//Do not edit this file

waitUntil {uiSleep 3; !isNil "A3XAI_locations_ready"};

call compile preprocessFileLineNumbers "A3XAI_config\A3XAI_custom_defs.sqf";

uiSleep 30;

A3XAI_customSpawnsReady = true;

if (A3XAI_debugLevel > 1) then {diag_log format ["A3XAI Debug: Custom spawns ready"];};
